Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
AllCops:
  Exclude:
    - config/initializers/secret_token.rb
